# Generated by Django 5.0 on 2023-12-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymenttransaction_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_no',
        ),
    ]
