# Generated by Django 5.0 on 2023-12-25 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('payments', '0003_remove_paymenttransaction_transaction_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=200)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=200)),
                ('state', models.ForeignKey(default=uuid.UUID('5ac61057-dce2-4d53-8dca-eff4e94c473d'), on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
