# Generated by Django 5.0 on 2024-01-01 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('consumer_key', models.CharField(blank=True, max_length=30, null=True)),
                ('consumer_secret', models.CharField(blank=True, max_length=30, null=True)),
                ('shortcode', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_key', models.CharField(blank=True, max_length=30, null=True)),
                ('auth_url', models.CharField(blank=True, max_length=30, null=True)),
                ('safaricom_api', models.CharField(blank=True, max_length=30, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('host_name', models.CharField(max_length=30)),
                ('till_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('trx_type', models.CharField(max_length=30)),
                ('environment', models.CharField(choices=[('STAGE', 'STAGE'), ('PRODUCTION', 'PRODUCTION')], default='STAGE', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
