# Generated by Django 4.1.2 on 2023-10-01 15:59

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('has_warranty', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=30, null=True)),
                ('further_location', models.CharField(default='Juja', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images')),
                ('is_purchased', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ADBid',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('is_top_category', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_link', models.CharField(max_length=300)),
                ('seo_txt', models.CharField(max_length=200)),
                ('seo_keyword', models.TextField(default='...')),
                ('author', models.CharField(default='sheltuz', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SheltuzUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('device', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SheltuzUser',
            },
        ),
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('state', models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='core_locati_name_65ac84_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='core_catego_name_6ef604_idx'),
        ),
        migrations.AddField(
            model_name='adbid',
            name='ad_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ad'),
        ),
        migrations.AddField(
            model_name='adbid',
            name='sheltuzUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sheltuzuser'),
        ),
        migrations.AddField(
            model_name='adbid',
            name='state',
            field=models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sheltuzuser'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.state'),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AddIndex(
            model_name='adbid',
            index=models.Index(fields=['sheltuzUser'], name='core_adbid_sheltuz_3016ac_idx'),
        ),
        migrations.AddIndex(
            model_name='adbid',
            index=models.Index(fields=['ad_product'], name='core_adbid_ad_prod_afb56e_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['name'], name='core_ad_name_7c13ad_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['price'], name='core_ad_price_09b540_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['condition'], name='core_ad_conditi_b74a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category'], name='core_ad_categor_fcc47c_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['location'], name='core_ad_locatio_f6cb81_idx'),
        ),
    ]
