# Generated by Django 4.2.4 on 2023-11-04 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('page_link', models.CharField(max_length=300)),
                ('seo_txt', models.CharField(max_length=200)),
                ('seo_keyword', models.TextField(default='...')),
                ('author', models.CharField(default='sheltuz', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
